In [135]:
import numpy as np

mapping={}
#create a dictionary
for i in range(27)[1:27]:
    mapping[chr(i+64)]=i
#give 0 for space
mapping[' ']=0

## The reversed dictionary will help us obtain letters by giving associated numbers
mapping_reversed={mapping[key]:key for key in mapping}

def replace_punctuation(word_list):
    word_list=[' ' if (ord(symbol) not in [i+65 for i in range(26)]) else symbol for symbol in word_list]
    return word_list, len(word_list)

def normalize_message(word_list):
    #if wordlist is not divisible by splitamount, add spaces
    #first find the nearest divisible number
    #subtract the len(word_list) from the number and save as noofspaces
    #add spaces noofspaces times   
    
    #we check only upto 100 multiples
    for multiple in [split_amount*m for m in range(100)]:
        if(multiple>word_list_length): #it cannot be equal because if it is equal it is divisible by the split amount
            amountofspaces=multiple-word_list_length
            break

    for s in range(amountofspaces):
        word_list.append(' ')
    return word_list

def make_message_matrix(word_list, split_amount):
    #Make the message_matrix(according to the split amount)
    #the split amount is equivalent the number of columns of the message matrix
    splitted=[] #to keep splitted characters
    message_matrix=[] #to keep codes
    for i in range(0, len(word_list),split_amount):
        splitted.append(word_list[i:i+split_amount])
        message_matrix.append([mapping[i] for i in word_list[i:i+split_amount]])
    return splitted, message_matrix

    
def encrypt(word,encoding_matrix):
    
    #covert word to upper_case
    word=word.upper()
    
    #In matrix multiplication number of columns of matrix a should match number of rows of matrix b
    #Therefore, we will use the the number of rows of the enconding matrix to be the number of columns
    #of the message matrix, this means the split length of the message

    split_amount=encoding_matrix.shape[0] 
    print "Split_amount(noofcolumns)= ", split_amount
    #convert string to list
    word_list=list(word)
    

    ##Replace punctuation by space
    word_list, word_list_length=replace_punctuation(word_list)
    print "Length of Message= ", word_list_length

    #if the number of letters is not divisible by split amount, add some spaces at the end
    if(word_list_length%split_amount!=0):
          word_list, word_list_length=normalize_word(word_list)

    splitted, message_matrix=make_message_matrix(word_list, split_amount)
  
    print "Message in Matrix Form\n", message_matrix
    #convert to numpy array
    message_matrix=np.array(message_matrix)
    #multiply the matrices and create coded row matrix
    encrypted_matrix=np.dot(message_matrix,encoding_matrix)
    #print coded_message
    print "encrypted_matrix \n", encrypted_matrix

    #unpack coded_message
    unpacked_encrypted_matrix=[j for i in encrypted_matrix for j in i ]
    #print unpacked_coded_message
    
    return encrypted_matrix, unpacked_encrypted_matrix

def decrypt(encoding_matrix, encrypted_matrix, singular):
    if singular:
        inverse_matrix=np.linalg.inv(encoding_matrix)
    else:
        inverse_matrix=np.around(np.linalg.pinv(encoding_matrix))
                                 
    print "Inverse_Matrix : "
    print inverse_matrix
    original=np.dot(encrypted_matrix,inverse_matrix)
    return [j for i in original for j in i ], [mapping_reversed[j] for i in original for j in i ]

In [136]:
#Example 1

#Encrypt first
word="MEET ME MONDAY."
print "Now Encrypting..."
encoding_matrix=np.array([[1,-2,2],[-1,1,3],[1,-1,-4]])
print "Encoding Matrix: "
print encoding_matrix
encrypted_matrix,unpacked_encrypted_matrix=encrypt(word, encoding_matrix)
print "encrypted form\n",unpacked_encrypted_matrix

##Decrypt Next
print "Now Decrypting..."
orginal_code, original_message=decrypt(encoding_matrix,encrypted_matrix, singular=True)
print "orignal message code\n", orginal_code
print "orignal message \n", original_message


Now Encrypting...
Encoding Matrix: 
[[ 1 -2  2]
 [-1  1  3]
 [ 1 -1 -4]]
Split_amount(noofcolumns)=  3
Length of Message=  15
Message in Matrix Form
[[13, 5, 5], [20, 0, 13], [5, 0, 13], [15, 14, 4], [1, 25, 0]]
encrypted_matrix 
[[ 13 -26  21]
 [ 33 -53 -12]
 [ 18 -23 -42]
 [  5 -20  56]
 [-24  23  77]]
encrypted form
[13, -26, 21, 33, -53, -12, 18, -23, -42, 5, -20, 56, -24, 23, 77]
Now Decrypting...
Inverse_Matrix : 
[[ -1. -10.  -8.]
 [ -1.  -6.  -5.]
 [ -0.  -1.  -1.]]
orignal message code
[13.0, 5.0, 5.0, 20.0, 0.0, 13.0, 5.0, 0.0, 13.0, 15.0, 14.0, 4.0, 1.0, 25.0, 0.0]
orignal message 
['M', 'E', 'E', 'T', ' ', 'M', 'E', ' ', 'M', 'O', 'N', 'D', 'A', 'Y', ' ']


In [137]:
#Example 2 A

##using an invertible matrix

#Encrypt first
word="PLEASE SEND MONEY."
print "Now Encrypting..."
encoding_matrix=np.array([[4,2,1],[-3,-3,-1],[3,2,1]])
print "Encoding Matrix: "
print encoding_matrix
encrypted_matrix,unpacked_encrypted_matrix=encrypt(word, encoding_matrix)
print "unpacked_encrypted_matrix \n",unpacked_encrypted_matrix

##Decrypt Next
print "Now Decrypting..."
orginal_code, original_message=decrypt(encoding_matrix,encrypted_matrix, singular=False)
print "orignal message code\n", orginal_code
print "orignal message \n", original_message

Now Encrypting...
Encoding Matrix: 
[[ 4  2  1]
 [-3 -3 -1]
 [ 3  2  1]]
Split_amount(noofcolumns)=  3
Length of Message=  18
Message in Matrix Form
[[16, 12, 5], [1, 19, 5], [0, 19, 5], [14, 4, 0], [13, 15, 14], [5, 25, 0]]
encrypted_matrix 
[[ 43   6   9]
 [-38 -45 -13]
 [-42 -47 -14]
 [ 44  16  10]
 [ 49   9  12]
 [-55 -65 -20]]
unpacked_encrypted_matrix 
[43, 6, 9, -38, -45, -13, -42, -47, -14, 44, 16, 10, 49, 9, 12, -55, -65, -20]
Now Decrypting...
Inverse_Matrix : 
[[ 1.  0. -1.]
 [ 0. -1. -1.]
 [-3.  2.  6.]]
orignal message code
[16.0, 12.0, 5.0, 1.0, 19.0, 5.0, 0.0, 19.0, 5.0, 14.0, 4.0, 0.0, 13.0, 15.0, 14.0, 5.0, 25.0, 0.0]
orignal message 
['P', 'L', 'E', 'A', 'S', 'E', ' ', 'S', 'E', 'N', 'D', ' ', 'M', 'O', 'N', 'E', 'Y', ' ']


In [138]:
#Example 2 B

#decrypting an encrypted text

encoding_matrix=encoding_matrix=np.array([[3,-4,2],[0,2,1],[4,-5,3]])
encrypted_matrix=np.array([[112,-140,83],[19,-25, 13], [72,-76, 61],[95,-118,71],[20,21,38],[35,-23,36],[42,-48,32]] )
orginal_code, original_message=decrypt(encoding_matrix,encrypted_matrix, singular=True)
print "orignal message code\n", orginal_code
print "orignal message \n", original_message

Inverse_Matrix : 
[[ 11.   2.  -8.]
 [  4.   1.  -3.]
 [ -8.  -1.   6.]]
orignal message code
[8.0, 1.0, 22.0, 5.0, 0.0, 1.0, 0.0, 7.0, 18.0, 5.0, 1.0, 20.0, 0.0, 23.0, 5.0, 5.0, 11.0, 5.0, 14.0, 4.0, 0.0]
orignal message 
['H', 'A', 'V', 'E', ' ', 'A', ' ', 'G', 'R', 'E', 'A', 'T', ' ', 'W', 'E', 'E', 'K', 'E', 'N', 'D', ' ']


In [144]:
##TGA trying matrix multiplication
#a=np.array([[1,2,3],[4,5,6]])
#b=np.array([[4,1],[3,3],[2,1]])

#print np.dot(a,b)


##TGA trying inverse of a matrix
#print np.linalg.inv([[3,0,2],[2,0,-2],[0,1,1]])
#print np.around(np.linalg.pinv([[3,0,2],[2,0,-2],[0,1,1]]))

##TGA trying shape

#Shape is a tuple not a function

#print a.shape[0]


##TGA trying list input

print "Please enter the encrypted matrix"
a = [int(x) for x in raw_input().split()]
print a

Please enter the encrypted matrix
1 2 3 4 19 3
[1, 2, 3, 4, 19, 3]


In [140]:
##Pinv is used for non-singular matrices
##inv is used for singular ones
#np.around will round all numbers to nearest one

print  np.around(np.linalg.pinv([[4,2,1],[-3,-3,-1],[3,2,1]]))

[[ 1.  0. -1.]
 [ 0. -1. -1.]
 [-3.  2.  6.]]


In [147]:
xdim,ydim=[1,2]
print xdim, ydim

1 2
